server:
  port: 8888
spring:
  application.name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/4neesh/HotelMicroservice
          searchPaths:
          - ConfigFiles*
          - ConfigFiles/vip*
eureka:
 client:
   serviceUrl:
     defaultZone: http://localhost:9001/eureka/